drop database activitylog;
create database activitylog;
use activitylog;

create table USUARIO (
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Identificacion INT PRIMARY KEY,
	Sexo VARCHAR(10) NOT NULL,
  Rol VARCHAR(12) NOT NULL,
	Password1 VARCHAR(40) NOT NULL
);

create table DEPARTAMENTO(
	ID_DEPTO int auto_increment primary key,
	NOMBRE VARCHAR(50) NOT NULL
);

create table ACTIVIDADES(
	ID_ACTIVIDAD int auto_increment primary key,
	TITULO VARCHAR(100),
  TITULAR INT NOT NULL,
  DEPARTAMENTO INT NOT NULL,
  FECHA_ACTIVIDAD DATETIME NOT NULL,
	FECHA_REGISTRO DATE NOT NULL,
  HORA_INICIO TIME NOT NULL,
  HORA_FINAL TIME NOT NULL,
  DESCRIPCION TEXT NOT NULL,
	FOREIGN KEY (TITULAR) REFERENCES USUARIO (Identificacion),
  FOREIGN KEY (DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPTO)
);
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Recursos humanos');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Dirección general');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Auxiliar administrativo');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Administración');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Finanzas y contabilidad');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Publicidad');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Tecnología');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Comercial');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Control');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Investigación');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Logística');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Atención al cliente');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Servicios generales');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Seguridad');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Almacén');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Jurídica');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Secretaría');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Proyectos');
INSERT INTO `DEPARTAMENTO` (`NOMBRE`) VALUES ('Infraestructura');

insert into actividades (titulo,titular,departamento,FECHA_ACTIVIDAD,FECHA_REGISTRO,HORA_INICIO,HORA_FINAL,DESCRIPCION) values ('titulo1','1233494730','1','2018-11-12 23:50:00','2018-11-12','23:12:59','23:15:59','Description');
